spring:
  application:
    name: kafka-test-app
  port: 8080
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAPSERVERS}

kafka-test-app:
  kafka:
    topics:
        name: com.mw.master.kafka
        partitions: 5
        replicationFactor: 1