server:
  port: ${SPRING_KAFKA_PORT}

spring:
  application:
    name: kafka-test-app
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAPSERVERS}
  mvc:
    async:
      request-timeout: -1

kafka-test-app:
  kafka:
    topics:
        name: ${SPRING_KAFKA_TOPIC_NAME}
        partitions: ${SPRING_KAFKA_PARTITIONS}
        replicationFactor: 1

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
