server:
  port: ${SPRING_KAFKA_PORT}

spring:
  application:
    name: kafka-test-app
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAPSERVERS}

kafka-test-app:
  kafka:
    topics:
        name: ${SPRING_KAFKA_TOPIC_NAME}
        partitions: ${SPRING_KAFKA_PARTITIONS}
        replicationFactor: 1