global:
  scrape_interval: 1s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'kafka-exporter'
    static_configs:
      - targets: ['kafka-exporter:9308']

  - job_name: 'producer'
    metrics_path: '/actuator/prometheus'
    dns_sd_configs:
      - names:
          - producer
        type: A
        port: 2200
  
  - job_name: 'consumer'
    metrics_path: '/actuator/prometheus'
    dns_sd_configs:
      - names:
          - consumer
        type: A
        port: 2000