server:
  port: ${SPRING_KAFKA_PORT}

spring:
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAPSERVERS}

kafka-test-app:
  kafka:
    topics:
      name: ${SPRING_KAFKA_TOPIC_NAME}

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
