{
 "title": "Kafka Exporter Dashboard",
 "tags": [ "Kafka" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Message in per second",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(kafka_topic_partition_current_offset{topic=\"com.mw.master.kafka\"}[1m])) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Message consume per second",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(delta(kafka_consumergroup_current_offset{topic=\"com.mw.master.kafka\"}[1m])/60) by (topic)",
     "legendFormat": "{{consumergroup}} (topic: {{topic}})"
    }
   ]
  },
  {
   "title": "Error ratio per second",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(spring_kafka_operations_total{type=\"error\"}[1m]))/(sum(rate(spring_kafka_operations_total{type=\"operation\"}[1m]))) * 100 > 0 or vector(0)",
     "legendFormat": "Error ratio per second"
    }
   ]
  },
  {
   "title": "end-to-end latency (ms)",
   "type": "heatmap",
   "gridPos": { "h": 21, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "sum by (upto) (rate(broker_latency_ms_total[1m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}