{
 "title": "Kafka Exporter Dashboardf",
 "description": "Kafka resource usage and throughput",
 "tags": [ "Kafka" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Message in per second",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(kafka_topic_partition_current_offset{topic=\"com.mw.master.kafka\"}[1m])) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Message consume per second",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(delta(kafka_consumergroup_current_offset{topic=\"com.mw.master.kafka\"}[1m])/60) by (topic)",
     "legendFormat": "{{consumergroup}} (topic: {{topic}})"
    }
   ]
  },
  {
   "title": "end-to-end latency (ms)",
   "type": "heatmap",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum by (upto) (rate(broker_latency_ms_total[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "errors total",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(send_errors_total)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Error rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 22 },
   "targets": [
    {
     "expr": "sum(rate(send_errors_total[1m]))",
     "legendFormat": "Errors per second"
    }
   ]
  }
 ]
}